version: '3.8'
services:
  fri:
    image: lunch:v10
    ports:
    - 30001:80
    environment:
    - TITLE_FILE=/title
    - COLOR=cyan
    deploy:
      replicas: 3
    configs:
    - title
  lunch:
    image: lalyos/12factor:boujee 
    ports:
    - 30002:80
    environment:
    - TITLE=Lunchtime
  web:
    image: nginx:alpine
    ports:
    - 30003:80
    configs:
    - source: html2
      target: /usr/share/nginx/html/index.html
    secrets:
    - source: top
      target: /usr/share/nginx/html/top.html


configs:
  html2:
    file: ./index.html
  title:
    file: ./title
secrets:
  top:
    file: ./topsecret.html