version: '3.3'
services:
  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=db.lvh.me
    ports:
    - 8080
  debuger:
    profiles:
      - debug
    image: alpine
    command: sleep 999
  lunch:
    # image: lalyos/lunch:v8
    build: .
    ports:
    - 80
    environment:
      - VIRTUAL_HOST=lunch.lvh.me
      - TITLE=${TITLE}
      - COLOR=${COLOR}
      - BODY=${BODY:-default}

networks:
  default:
    external:
      name: infra_default