version: '3.3'
services:
  adminer:
    image: adminer
    environment:
      - VIRTUAL_HOST=db.lvh.me
    ports:
    - 8080
  dev:
    build: dev
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    command: sleep 9999
  lunch:
    # image: lalyos/lunch:v8
    build: .
    ports:
    - 80
    environment:
      - VIRTUAL_HOST=lunch.lvh.me
      - TITLE=${TITLE}
      - COLOR=${COLOR}
      - BODY=${BODY:-default}
    labels:
      - "traefik.frontend.rule=Host:lunch.${DOMAIN:-lvh.me}"
networks:
  default:
    name: infra