version: '3.3'
services:
  mydb:
    environment:
    - POSTGRES_PASSWORD=secret
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
    - mydb:/var/lib/postgresql/data
    image: postgres:15.1
  adminer:
    image: adminer
    ports:
    - 8080
  lunch:
    image: lalyos/lunch:v8
    ports:
    - 80
    environment:
      - TITLE=Lunchtime
      - COLOR=HotPink
      - BODY=<iframe src="https://giphy.com/embed/11dgYWwHnEFomQ" width="259" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/cat-eating-11dgYWwHnEFomQ">via GIPHY</a></p>
  registry:
    image: registry:2
    ports:
    - 5000:5000
volumes:
  mydb: